### ISSUE TITLE
Add Coordinate Search Support

### ISSUE THREAD

**Issue by surya27895** [Android1500/GpsSetter#14]
Hi,

As the title says, I hope you can add support for coordinate search, sometime its more useful to set gps at long-lat coordinates instead of city name,
Please considered it, thanks.

Best regards.

**Comment by Android1500** [comment]
> Hi,
> 
> 
> 
> As the title says, I hope you can add support for coordinate search, sometime its more useful to set gps at long-lat coordinates instead of city name,
> 
> Please considered it, thanks.
> 
> 
> 
> Best regards.

all ready added

**Comment by surya27895** [comment]
oh i don't realize it since last update, thanks

**Comment by Android1500** [comment]
> oh i don't realize it since last update, thanks

Yah just write coordinates in search box like 37.7749, -122.4194 and search it.
