### ISSUE TITLE
Please remove StartApp

### ISSUE THREAD

**Issue by IzzySoft** [Android1500/GpsSetter#17]
Just a kindly request: would you please remove the StartApp SDK? With your app running as Xposed module, it has elevated privileges. This access should not be given to proprietary ad and/or tracking libraries, which inherit the permissions of its host app.

Thanks in advance!

**Comment by Android1500** [comment]
As you want i just removed StartApp SDK but now its hard to alive this project so maybe it will die soon.

**Comment by IzzySoft** [comment]
Yeah, that's a conflict, and understandable. Not sure if there are any trustable FOSS alternatives (I've not yet found any). But as that's the policy in my repo (no proprietary ad/tracking modules with root apps, health data, children apps, password apps and other apps processing sensitive data), I had to remove the update from my repo and disable auto-updates for now.

Maybe we can have a compromise: could you provide a version without StartApp in addition to the regular one, so I could use that via my repo? The majority of your users will probably install it by other means (XDA, some Xposed repo like EdXposed or LSPosed one – xposed.info unfortunately is down) anyway, so it would not make that much difference to you. Users of my repo are rather out for privacy.

For reference: [this](https://apt.izzysoft.de/fdroid/index/apk/com.android1500.gpssetter) is the listing I'm talking about.

**Comment by Android1500** [comment]
you don't need to worry i just removed and release v1.2.10 without StartApp SDK

**Comment by IzzySoft** [comment]
PS: Just pulled the new APK and re-established it, thanks! Please take care with `versionCode`, which was just increased from 129 to 1210 – you can never decrease again as that's what Android uses to tell versions apart: higher `versionCode` = update, lower = no update possible as it's considered a downgrade.

Update will become visible with the next sync tomorrow (updater runs once per day).

**Comment by IzzySoft** [comment]
PPS: should I ever find some privacy-friendly foss ad modules, I'll [add them here](https://gitlab.com/-/snippets/1896503) to my corresponding hints.

**Comment by IzzySoft** [comment]
FYI: I've just raised the issue here: [any privacy-friendly, FOSS advertisement modules for Android?](https://softwarerecs.stackexchange.com/q/84485/185)

**Comment by Android1500** [comment]
> PS: Just pulled the new APK and re-established it, thanks! Please take care with `versionCode`, which was just increased from 129 to 1210 – you can never decrease again as that's what Android uses to tell versions apart: higher `versionCode` = update, lower = no update possible as it's considered a downgrade.
> 
> 
> 
> Update will become visible with the next sync tomorrow (updater runs once per day).

Yah i know its not a issue
