### ISSUE TITLE
The default location is error

### ISSUE THREAD

**Issue by pingping1314520** [Android1500/GpsSetter#2]
When I followed the steps to set the GPSsetter，I found my device was wrongly positioned in Kazakhstan.And my actual location is in China.

**Comment by Android1500** [comment]
> When I followed the steps to set the GPSsetter，I found my device was wrongly positioned in Kazakhstan.And my actual location is in China.

are you selected system frameworks?

**Comment by pingping1314520** [comment]
> > When I followed the steps to set the GPSsetter，I found my device was wrongly positioned in Kazakhstan.And my actual location is in China.
> 
> are you selected system frameworks?

yes.I select system frameworks and a delivery app that I want to hook.

**Comment by Android1500** [comment]
> > > When I followed the steps to set the GPSsetter，I found my device was wrongly positioned in Kazakhstan.And my actual location is in China.
> > 
> > 
> > are you selected system frameworks?
> 
> yes.I select system frameworks and a delivery app that I want to hook.

don't select it

**Comment by pingping1314520** [comment]
> > > > When I followed the steps to set the GPSsetter，I found my device was wrongly positioned in Kazakhstan.And my actual location is in China.
> > > 
> > > 
> > > are you selected system frameworks?
> > 
> > yes.I select system frameworks and a delivery app that I want to hook.
> 
> don't select it  and reboot device and try

I tried but it doesn't work.Then I reinstalled the GPS setter and this time my devices was wrongly positioned in Hong Kong😂I don't know why.

**Comment by Android1500** [comment]
> > > > > When I followed the steps to set the GPSsetter，I found my device was wrongly positioned in Kazakhstan.And my actual location is in China.
> > > > 
> > > > 
> > > > are you selected system frameworks?
> > > 
> > > 
> > > yes.I select system frameworks and a delivery app that I want to hook.
> > 
> > 
> > don't select it  and reboot device and try
> 
> I tried but it doesn't work.Then I reinstalled the GPS setter and this time my devices was wrongly positioned in Hong Kong😂I don't know why.

strange lets try first uninstall it then reboot device after reboot again install it and select target app and reboot device and check again

**Comment by pingping1314520** [comment]
> > > > > > When I followed the steps to set the GPSsetter，I found my device was wrongly positioned in Kazakhstan.And my actual location is in China.
> > > > > 
> > > > > 
> > > > > are you selected system frameworks?
> > > > 
> > > > 
> > > > yes.I select system frameworks and a delivery app that I want to hook.
> > > 
> > > 
 for your> > > don't select it  and reboot device and try
> > 
> > I tried but it doesn't work.Then I reinstalled the GPS setter and this time my devices was wrongly positioned in Hong Kong😂I don't know why.
> 
> strange lets try first uninstall it then reboot device after reboot again install it and select target app and reboot device and check again(Don't select system)

I followed your sreps but it still doesn't work🙁🙁.My default location is still in Hong Kong.Really strange!Well,at least the function to change location is normal use.Thanks for your reply.
