### ISSUE TITLE
add bearing , accuracy, altitude

### ISSUE THREAD

**Issue by simonbuehler** [Android1500/GpsSetter#7]
hi, nice project as with A12 smalipatcher wouldn't work, maybe you can get som ideas from https://forum.xda-developers.com/t/xposed-pokemon-go-controls-xposed-module.3421247/post-77474789 , the zip targets pogo but the hooks should be universal ( don't know if the api changed much since then ), maybe a joystick soon ;) ?

**Comment by Android1500** [comment]
Hye @simonbuehler , I am going to take a look at zip and yes I will add joystick but latter and its also in my features roadmap but recently I am focusing on learning jetpack compose so coz of this adding any new features in GPS Setter will be delay.

**Comment by Android1500** [comment]
Added

**Comment by RevealedSoulEven** [comment]
> Added

Where is the option available?

**Comment by Android1500** [comment]
just update latest version you will get accuracy option in setting

**Comment by RevealedSoulEven** [comment]
> just update latest version you will get accuracy option in setting

Yes it is there, but what the accuracy option really is?

**Comment by simonbuehler** [comment]
> > just update latest version you will get accuracy option in setting
> 
> Yes it is there, but what the accuracy option really is?

https://developer.android.com/reference/android/location/Location.html#getAccuracy()
